modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Iskallia/Vault/issues" #optional
[[mods]]
modId="the_vault"
version="${file.jarVersion}"
displayName="The Vault"
description='''
Vault mod for Vault Hunters Series
'''
[[dependencies.the_vault]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.the_vault]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"
