package iskallia.vault.init;

import iskallia.vault.skill.ability.AbilityRegistry;
import iskallia.vault.skill.ability.effect.DashAbility;
import iskallia.vault.skill.ability.effect.ExecuteAbility;
import iskallia.vault.skill.ability.effect.FarmerAbility;
import iskallia.vault.skill.ability.effect.GhostWalkAbility;
import iskallia.vault.skill.ability.effect.HealAbility;
import iskallia.vault.skill.ability.effect.HunterAbility;
import iskallia.vault.skill.ability.effect.ManaShieldAbility;
import iskallia.vault.skill.ability.effect.MegaJumpAbility;
import iskallia.vault.skill.ability.effect.NovaAbility;
import iskallia.vault.skill.ability.effect.RampageAbility;
import iskallia.vault.skill.ability.effect.SummonEternalAbility;
import iskallia.vault.skill.ability.effect.TankAbility;
import iskallia.vault.skill.ability.effect.TauntAbility;
import iskallia.vault.skill.ability.effect.VeinMinerAbility;
import iskallia.vault.skill.ability.effect.sub.DashDamageAbility;
import iskallia.vault.skill.ability.effect.sub.FarmerAnimalAbility;
import iskallia.vault.skill.ability.effect.sub.FarmerCactusAbility;
import iskallia.vault.skill.ability.effect.sub.FarmerMelonAbility;
import iskallia.vault.skill.ability.effect.sub.HealEffectAbility;
import iskallia.vault.skill.ability.effect.sub.HealGroupAbility;
import iskallia.vault.skill.ability.effect.sub.HunterObjectiveAbility;
import iskallia.vault.skill.ability.effect.sub.MegaJumpBreakDownAbility;
import iskallia.vault.skill.ability.effect.sub.MegaJumpBreakUpAbility;
import iskallia.vault.skill.ability.effect.sub.NovaDotAbility;
import iskallia.vault.skill.ability.effect.sub.NovaSpeedAbility;
import iskallia.vault.skill.ability.effect.sub.RampageChainAbility;
import iskallia.vault.skill.ability.effect.sub.RampageLeechAbility;
import iskallia.vault.skill.ability.effect.sub.TankProjectileAbility;
import iskallia.vault.skill.ability.effect.sub.TankReflectAbility;
import iskallia.vault.skill.ability.effect.sub.TauntRepelAbility;
import iskallia.vault.skill.ability.effect.sub.VeinMinerDurabilityAbility;
import iskallia.vault.skill.ability.effect.sub.VeinMinerFortuneAbility;
import iskallia.vault.skill.ability.effect.sub.VeinMinerVoidAbility;

public class ModAbilities {
   public static final String HEAL = "Heal";
   public static final String HEAL_EFFECT = "Heal_Effect";
   public static final String HEAL_GROUP = "Heal_Group";
   public static final String DASH = "Dash";
   public static final String DASH_DAMAGE = "Dash_Damage";
   public static final String NOVA = "Nova";
   public static final String NOVA_SPEED = "Nova_Speed";
   public static final String NOVA_DOT = "Nova_Dot";
   public static final String EXECUTE = "Execute";
   public static final String GHOST_WALK = "Ghost Walk";
   public static final String MEGA_JUMP = "Mega Jump";
   public static final String MEGA_JUMP_BREAK_UP = "Mega Jump_Break_Up";
   public static final String MEGA_JUMP_BREAK_DOWN = "Mega Jump_Break_Down";
   public static final String RAMPAGE = "Rampage";
   public static final String RAMPAGE_LEECH = "Rampage_Leech";
   public static final String RAMPAGE_CHAIN = "Rampage_Chain";
   public static final String SUMMON_ETERNAL = "Summon Eternal";
   public static final String TANK = "Tank";
   public static final String TANK_PROJECTILE = "Tank_Projectile";
   public static final String TANK_REFLECT = "Tank_Reflect";
   public static final String VEIN_MINER = "Vein Miner";
   public static final String VEIN_MINER_FORTUNE = "Vein Miner_Fortune";
   public static final String VEIN_MINER_DURABILITY = "Vein Miner_Durability";
   public static final String VEIN_MINER_VOID = "Vein Miner_Void";
   public static final String HUNTER = "Hunter";
   public static final String HUNTER_BLOCKS = "Hunter_Blocks";
   public static final String FARMER = "Farmer";
   public static final String FARMER_MELON = "Farmer_Melon";
   public static final String FARMER_CACTUS = "Farmer_Cactus";
   public static final String FARMER_ANIMAL = "Farmer_Animal";
   public static final String MANA_SHIELD = "Mana Shield";
   public static final String TAUNT = "Taunt";
   public static final String TAUNT_REPEL = "Taunt_Repel";

   public static void init() {
      AbilityRegistry.register("Heal", new HealAbility());
      AbilityRegistry.register("Heal_Effect", new HealEffectAbility(HealEffectAbility.RemovalStrategy.DEFINED_ONLY));
      AbilityRegistry.register("Heal_Group", new HealGroupAbility());
      AbilityRegistry.register("Dash", new DashAbility());
      AbilityRegistry.register("Dash_Damage", new DashDamageAbility());
      AbilityRegistry.register("Nova", new NovaAbility());
      AbilityRegistry.register("Nova_Speed", new NovaSpeedAbility());
      AbilityRegistry.register("Nova_Dot", new NovaDotAbility());
      AbilityRegistry.register("Ghost Walk", new GhostWalkAbility());
      AbilityRegistry.register("Mega Jump", new MegaJumpAbility());
      AbilityRegistry.register("Mega Jump_Break_Up", new MegaJumpBreakUpAbility());
      AbilityRegistry.register("Mega Jump_Break_Down", new MegaJumpBreakDownAbility());
      AbilityRegistry.register("Hunter", new HunterAbility());
      AbilityRegistry.register("Hunter_Blocks", new HunterObjectiveAbility());
      AbilityRegistry.register("Execute", new ExecuteAbility());
      AbilityRegistry.register("Summon Eternal", new SummonEternalAbility());
      AbilityRegistry.register("Farmer", new FarmerAbility());
      AbilityRegistry.register("Farmer_Melon", new FarmerMelonAbility());
      AbilityRegistry.register("Farmer_Cactus", new FarmerCactusAbility());
      AbilityRegistry.register("Farmer_Animal", new FarmerAnimalAbility());
      AbilityRegistry.register("Mana Shield", new ManaShieldAbility());
      AbilityRegistry.register("Tank", new TankAbility());
      AbilityRegistry.register("Tank_Projectile", new TankProjectileAbility());
      AbilityRegistry.register("Tank_Reflect", new TankReflectAbility());
      AbilityRegistry.register("Rampage", new RampageAbility());
      AbilityRegistry.register("Rampage_Leech", new RampageLeechAbility());
      AbilityRegistry.register("Rampage_Chain", new RampageChainAbility());
      AbilityRegistry.register("Taunt", new TauntAbility());
      AbilityRegistry.register("Taunt_Repel", new TauntRepelAbility());
      AbilityRegistry.register("Vein Miner", new VeinMinerAbility());
      AbilityRegistry.register("Vein Miner_Fortune", new VeinMinerFortuneAbility());
      AbilityRegistry.register("Vein Miner_Durability", new VeinMinerDurabilityAbility());
      AbilityRegistry.register("Vein Miner_Void", new VeinMinerVoidAbility());
   }
}
