package iskallia.vault.init;

public class ModAbilities {
   public static final String HEAL = "Heal";
   public static final String HEAL_EFFECT = "Heal_Effect";
   public static final String HEAL_GROUP = "Heal_Group";
   public static final String DASH = "Dash";
   public static final String DASH_DAMAGE = "Dash_Damage";
   public static final String DASH_WARP = "Dash_Warp";
   public static final String NOVA = "Nova";
   public static final String NOVA_SPEED = "Nova_Speed";
   public static final String NOVA_DOT = "Nova_Dot";
   public static final String EXECUTE = "Execute";
   public static final String GHOST_WALK = "Ghost Walk";
   public static final String GHOST_WALK_SPIRIT_WALK = "Ghost Walk_Spirit_Walk";
   public static final String MEGA_JUMP = "Mega Jump";
   public static final String MEGA_JUMP_BREAK_UP = "Mega Jump_Break_Up";
   public static final String MEGA_JUMP_BREAK_DOWN = "Mega Jump_Break_Down";
   public static final String RAMPAGE = "Rampage";
   public static final String RAMPAGE_LEECH = "Rampage_Leech";
   public static final String RAMPAGE_CHAIN = "Rampage_Chain";
   public static final String SUMMON_ETERNAL = "Summon Eternal";
   public static final String EMPOWER = "Empower";
   public static final String EMPOWER_ICE_ARMOUR = "Empower_Ice_Armour";
   public static final String EMPOWER_SLOWNESS_AURA = "Empower_Slowness_Aura";
   public static final String SHELL_PORCUPINE = "Shell_Porcupine";
   public static final String VEIN_MINER = "Vein Miner";
   public static final String VEIN_MINER_FORTUNE = "Vein Miner_Fortune";
   public static final String VEIN_MINER_DURABILITY = "Vein Miner_Durability";
   public static final String VEIN_MINER_VOID = "Vein Miner_Void";
   public static final String HUNTER = "Hunter";
   public static final String HUNTER_BLOCKS = "Hunter_Blocks";
   public static final String HUNTER_WOODEN = "Hunter_Wooden";
   public static final String HUNTER_GILDED = "Hunter_Gilded";
   public static final String HUNTER_LIVING = "Hunter_Living";
   public static final String HUNTER_ORNATE = "Hunter_Ornate";
   public static final String HUNTER_COINS = "Hunter_Coins";
   public static final String FARMER = "Farmer";
   public static final String FARMER_MELON = "Farmer_Melon";
   public static final String FARMER_CACTUS = "Farmer_Cactus";
   public static final String FARMER_ANIMAL = "Farmer_Animal";
   public static final String MANA_SHIELD = "Mana Shield";
   public static final String MANA_SHIELD_RETRIBUTION = "Mana Shield_Retribution";
   public static final String TAUNT = "Taunt";
   public static final String TAUNT_REPEL = "Taunt_Repel";
   public static final String TAUNT_CHARM = "Taunt_Charm";
   public static final String STONEFALL = "Stonefall";
   public static final String STONEFALL_SNOW = "Stonefall_Snow";
   public static final String STONEFALL_COLD = "Stonefall_Cold";
   public static final String TOTEM = "Totem";
   public static final String TOTEM_MOB_DAMAGE = "Totem_Mob_Damage";
   public static final String TOTEM_MANA_REGEN = "Totem_Mana_Regen";
   public static final String TOTEM_PLAYER_DAMAGE = "Totem_Player_Damage";
   public static final String JAVELIN = "Javelin";
   public static final String JAVELIN_PIERCING = "Javelin_Piercing";
   public static final String JAVELIN_SCATTER = "Javelin_Scatter";
   public static final String JAVELIN_SIGHT = "Javelin_Sight";
   public static final String SMITE = "Smite";
   public static final String SMITE_ARCHON = "Smite_Archon";
   public static final String SMITE_THUNDERSTORM = "Smite_Thunderstorm";
   public static final String SHELL = "Shell";
   public static final String SHELL_QUILL = "Shell_Quill";
   public static final String FIREBALL = "Fireball";
   public static final String FIREBALL_VOLLEY = "Fireball_Volley";
   public static final String FIREBALL_FIRESHOT = "Fireball_Fireshot";
   public static final String STORM_ARROW_THUNDERSTORM = "Storm Arrow: Thunderstorm";
   public static final String STORM_ARROW_BLIZZARD = "Storm Arrow: Blizzard";
   public static final String BATTLE_CRY = "Battle_Cry";
   public static final String BATTLE_CRY_SPECTRAL_STRIKE = "Battle_Cry_Spectral_Strike";
   public static final String BATTLE_CRY_LUCKY_STRIKE = "Battle_Cry_Lucky_Strike";

   public static void init() {
   }
}
