package iskallia.vault.init;

import iskallia.vault.Vault;
import iskallia.vault.config.AbilitiesConfig;
import iskallia.vault.config.AbilitiesGUIConfig;
import iskallia.vault.config.ArchitectEventConfig;
import iskallia.vault.config.ConsumablesConfig;
import iskallia.vault.config.CryoChamberConfig;
import iskallia.vault.config.DifficultyDescriptionConfig;
import iskallia.vault.config.DurabilityConfig;
import iskallia.vault.config.EtchingConfig;
import iskallia.vault.config.EternalAttributeConfig;
import iskallia.vault.config.EternalAuraConfig;
import iskallia.vault.config.EternalConfig;
import iskallia.vault.config.FlawedRubyConfig;
import iskallia.vault.config.GlobalTraderConfig;
import iskallia.vault.config.KeyPressRecipesConfig;
import iskallia.vault.config.LegendaryTreasureEpicConfig;
import iskallia.vault.config.LegendaryTreasureNormalConfig;
import iskallia.vault.config.LegendaryTreasureOmegaConfig;
import iskallia.vault.config.LegendaryTreasureRareConfig;
import iskallia.vault.config.LootTablesConfig;
import iskallia.vault.config.ModBoxConfig;
import iskallia.vault.config.MysteryBoxConfig;
import iskallia.vault.config.MysteryEggConfig;
import iskallia.vault.config.MysteryHostileEggConfig;
import iskallia.vault.config.OverLevelEnchantConfig;
import iskallia.vault.config.PandorasBoxConfig;
import iskallia.vault.config.PaxelEnhancementConfig;
import iskallia.vault.config.PlayerScalingConfig;
import iskallia.vault.config.RaidConfig;
import iskallia.vault.config.RaidEventConfig;
import iskallia.vault.config.RaidModifierConfig;
import iskallia.vault.config.ResearchConfig;
import iskallia.vault.config.ResearchGroupConfig;
import iskallia.vault.config.ResearchGroupStyleConfig;
import iskallia.vault.config.ResearchesGUIConfig;
import iskallia.vault.config.ScavengerHuntConfig;
import iskallia.vault.config.SetsConfig;
import iskallia.vault.config.SkillDescriptionsConfig;
import iskallia.vault.config.SkillGatesConfig;
import iskallia.vault.config.SoulShardConfig;
import iskallia.vault.config.StatueLootConfig;
import iskallia.vault.config.StatueRecyclingConfig;
import iskallia.vault.config.TalentsConfig;
import iskallia.vault.config.TalentsGUIConfig;
import iskallia.vault.config.TraderCoreConfig;
import iskallia.vault.config.UnidentifiedTreasureKeyConfig;
import iskallia.vault.config.UnknownEggConfig;
import iskallia.vault.config.VaultAltarConfig;
import iskallia.vault.config.VaultCharmConfig;
import iskallia.vault.config.VaultChestConfig;
import iskallia.vault.config.VaultCrystalCatalystConfig;
import iskallia.vault.config.VaultCrystalConfig;
import iskallia.vault.config.VaultGearConfig;
import iskallia.vault.config.VaultGearCraftingScalingConfig;
import iskallia.vault.config.VaultGearScalingConfig;
import iskallia.vault.config.VaultGearUpgradeConfig;
import iskallia.vault.config.VaultGearUtilitiesConfig;
import iskallia.vault.config.VaultGeneralConfig;
import iskallia.vault.config.VaultInhibitorConfig;
import iskallia.vault.config.VaultItemsConfig;
import iskallia.vault.config.VaultLevelsConfig;
import iskallia.vault.config.VaultLootablesConfig;
import iskallia.vault.config.VaultMetaChestConfig;
import iskallia.vault.config.VaultMobsConfig;
import iskallia.vault.config.VaultModifiersConfig;
import iskallia.vault.config.VaultPortalConfig;
import iskallia.vault.config.VaultRelicsConfig;
import iskallia.vault.config.VaultRuneConfig;
import iskallia.vault.config.VaultScalingChestConfig;
import iskallia.vault.config.VaultSizeConfig;
import iskallia.vault.config.VaultStewConfig;
import iskallia.vault.config.VaultUtilitiesConfig;

public class ModConfigs {
   public static AbilitiesConfig ABILITIES;
   public static AbilitiesGUIConfig ABILITIES_GUI;
   public static TalentsConfig TALENTS;
   public static TalentsGUIConfig TALENTS_GUI;
   public static ResearchConfig RESEARCHES;
   public static ResearchesGUIConfig RESEARCHES_GUI;
   public static ResearchGroupConfig RESEARCH_GROUPS;
   public static ResearchGroupStyleConfig RESEARCH_GROUP_STYLES;
   public static SkillDescriptionsConfig SKILL_DESCRIPTIONS;
   public static SkillGatesConfig SKILL_GATES;
   public static VaultLevelsConfig LEVELS_META;
   public static VaultRelicsConfig VAULT_RELICS;
   public static VaultMobsConfig VAULT_MOBS;
   public static VaultItemsConfig VAULT_ITEMS;
   public static VaultAltarConfig VAULT_ALTAR;
   public static VaultGeneralConfig VAULT_GENERAL;
   public static VaultCrystalConfig VAULT_CRYSTAL;
   public static VaultPortalConfig VAULT_PORTAL;
   public static LegendaryTreasureNormalConfig LEGENDARY_TREASURE_NORMAL;
   public static LegendaryTreasureRareConfig LEGENDARY_TREASURE_RARE;
   public static LegendaryTreasureEpicConfig LEGENDARY_TREASURE_EPIC;
   public static LegendaryTreasureOmegaConfig LEGENDARY_TREASURE_OMEGA;
   public static StatueLootConfig STATUE_LOOT;
   public static CryoChamberConfig CRYO_CHAMBER;
   public static KeyPressRecipesConfig KEY_PRESS;
   public static OverLevelEnchantConfig OVERLEVEL_ENCHANT;
   public static VaultStewConfig VAULT_STEW;
   public static MysteryBoxConfig MYSTERY_BOX;
   public static VaultModifiersConfig VAULT_MODIFIERS;
   public static TraderCoreConfig.TraderCoreCommonConfig TRADER_CORE_COMMON;
   public static PandorasBoxConfig PANDORAS_BOX;
   public static EternalConfig ETERNAL;
   public static VaultGearConfig VAULT_GEAR_SCRAPPY;
   public static VaultGearConfig VAULT_GEAR_COMMON;
   public static VaultGearConfig VAULT_GEAR_RARE;
   public static VaultGearConfig VAULT_GEAR_EPIC;
   public static VaultGearConfig VAULT_GEAR_OMEGA;
   public static VaultGearConfig.General VAULT_GEAR;
   public static SetsConfig SETS;
   public static GlobalTraderConfig GLOBAL_TRADER;
   public static VaultLootablesConfig VAULT_LOOTABLES;
   public static VaultChestConfig VAULT_CHEST;
   public static VaultChestConfig VAULT_TREASURE_CHEST;
   public static VaultChestConfig VAULT_ALTAR_CHEST;
   public static VaultChestConfig VAULT_COOP_CHEST;
   public static VaultChestConfig VAULT_BONUS_CHEST;
   public static VaultMetaChestConfig VAULT_CHEST_META;
   public static StatueRecyclingConfig STATUE_RECYCLING;
   public static UnknownEggConfig UNKNOWN_EGG;
   public static ConsumablesConfig CONSUMABLES;
   public static LootTablesConfig LOOT_TABLES;
   public static VaultUtilitiesConfig VAULT_UTILITIES;
   public static VaultCrystalCatalystConfig VAULT_CRYSTAL_CATALYST;
   public static PlayerScalingConfig PLAYER_SCALING;
   public static PaxelEnhancementConfig PAXEL_ENHANCEMENTS;
   public static ScavengerHuntConfig SCAVENGER_HUNT;
   public static DurabilityConfig DURBILITY;
   public static ModBoxConfig MOD_BOX;
   public static ArchitectEventConfig ARCHITECT_EVENT;
   public static UnidentifiedTreasureKeyConfig UNIDENTIFIED_TREASURE_KEY;
   public static VaultGearUpgradeConfig VAULT_GEAR_UPGRADE;
   public static VaultGearScalingConfig VAULT_GEAR_SCALING;
   public static VaultSizeConfig VAULT_SIZE;
   public static SoulShardConfig SOUL_SHARD;
   public static EternalAttributeConfig ETERNAL_ATTRIBUTES;
   public static EternalAuraConfig ETERNAL_AURAS;
   public static VaultGearUtilitiesConfig VAULT_GEAR_UTILITIES;
   public static VaultGearCraftingScalingConfig VAULT_GEAR_CRAFTING_SCALING;
   public static DifficultyDescriptionConfig DIFFICULTY_DESCRIPTION;
   public static VaultScalingChestConfig SCALING_CHEST_REWARDS;
   public static VaultInhibitorConfig VAULT_INHIBITOR;
   public static FlawedRubyConfig FLAWED_RUBY;
   public static EtchingConfig ETCHING;
   public static RaidConfig RAID_CONFIG;
   public static RaidModifierConfig RAID_MODIFIER_CONFIG;
   public static RaidEventConfig RAID_EVENT_CONFIG;
   public static VaultCharmConfig VAULT_CHARM;
   public static MysteryEggConfig MYSTERY_EGG;
   public static MysteryHostileEggConfig MYSTERY_HOSTILE_EGG;
   public static VaultRuneConfig VAULT_RUNE;

   public static void registerCompressionConfigs() {
   }

   public static void register() {
      ABILITIES = new AbilitiesConfig().readConfig();
      ABILITIES_GUI = new AbilitiesGUIConfig().readConfig();
      TALENTS = new TalentsConfig().readConfig();
      TALENTS_GUI = new TalentsGUIConfig().readConfig();
      RESEARCHES = new ResearchConfig().readConfig();
      RESEARCHES_GUI = new ResearchesGUIConfig().readConfig();
      RESEARCH_GROUPS = new ResearchGroupConfig().readConfig();
      RESEARCH_GROUP_STYLES = new ResearchGroupStyleConfig().readConfig();
      SKILL_DESCRIPTIONS = new SkillDescriptionsConfig().readConfig();
      SKILL_GATES = new SkillGatesConfig().readConfig();
      LEVELS_META = new VaultLevelsConfig().readConfig();
      VAULT_RELICS = new VaultRelicsConfig().readConfig();
      VAULT_MOBS = new VaultMobsConfig().readConfig();
      VAULT_ITEMS = new VaultItemsConfig().readConfig();
      VAULT_ALTAR = new VaultAltarConfig().readConfig();
      VAULT_GENERAL = new VaultGeneralConfig().readConfig();
      VAULT_CRYSTAL = new VaultCrystalConfig().readConfig();
      VAULT_PORTAL = new VaultPortalConfig().readConfig();
      LEGENDARY_TREASURE_NORMAL = new LegendaryTreasureNormalConfig().readConfig();
      LEGENDARY_TREASURE_RARE = new LegendaryTreasureRareConfig().readConfig();
      LEGENDARY_TREASURE_EPIC = new LegendaryTreasureEpicConfig().readConfig();
      LEGENDARY_TREASURE_OMEGA = new LegendaryTreasureOmegaConfig().readConfig();
      STATUE_LOOT = new StatueLootConfig().readConfig();
      CRYO_CHAMBER = new CryoChamberConfig().readConfig();
      KEY_PRESS = new KeyPressRecipesConfig().readConfig();
      OVERLEVEL_ENCHANT = new OverLevelEnchantConfig().readConfig();
      VAULT_STEW = new VaultStewConfig().readConfig();
      MYSTERY_BOX = new MysteryBoxConfig().readConfig();
      VAULT_MODIFIERS = new VaultModifiersConfig().readConfig();
      TRADER_CORE_COMMON = new TraderCoreConfig.TraderCoreCommonConfig().readConfig();
      PANDORAS_BOX = new PandorasBoxConfig().readConfig();
      ETERNAL = new EternalConfig().readConfig();
      VAULT_GEAR_SCRAPPY = new VaultGearConfig.Scrappy().readConfig();
      VAULT_GEAR_COMMON = new VaultGearConfig.Common().readConfig();
      VAULT_GEAR_RARE = new VaultGearConfig.Rare().readConfig();
      VAULT_GEAR_EPIC = new VaultGearConfig.Epic().readConfig();
      VAULT_GEAR_OMEGA = new VaultGearConfig.Omega().readConfig();
      VAULT_GEAR = new VaultGearConfig.General().readConfig();
      SETS = new SetsConfig().readConfig();
      GLOBAL_TRADER = new GlobalTraderConfig().readConfig();
      VAULT_LOOTABLES = new VaultLootablesConfig().readConfig();
      VAULT_CHEST = new VaultChestConfig("vault_chest").readConfig();
      VAULT_TREASURE_CHEST = new VaultChestConfig("vault_treasure_chest").readConfig();
      VAULT_ALTAR_CHEST = new VaultChestConfig("vault_altar_chest").readConfig();
      VAULT_COOP_CHEST = new VaultChestConfig("vault_coop_chest").readConfig();
      VAULT_BONUS_CHEST = new VaultChestConfig("vault_bonus_chest").readConfig();
      VAULT_CHEST_META = new VaultMetaChestConfig().readConfig();
      STATUE_RECYCLING = new StatueRecyclingConfig().readConfig();
      UNKNOWN_EGG = new UnknownEggConfig().readConfig();
      CONSUMABLES = new ConsumablesConfig().readConfig();
      LOOT_TABLES = new LootTablesConfig().readConfig();
      VAULT_UTILITIES = new VaultUtilitiesConfig().readConfig();
      VAULT_CRYSTAL_CATALYST = new VaultCrystalCatalystConfig().readConfig();
      PLAYER_SCALING = new PlayerScalingConfig().readConfig();
      PAXEL_ENHANCEMENTS = new PaxelEnhancementConfig().readConfig();
      SCAVENGER_HUNT = new ScavengerHuntConfig().readConfig();
      DURBILITY = new DurabilityConfig().readConfig();
      MOD_BOX = new ModBoxConfig().readConfig();
      ARCHITECT_EVENT = new ArchitectEventConfig().readConfig();
      UNIDENTIFIED_TREASURE_KEY = new UnidentifiedTreasureKeyConfig().readConfig();
      VAULT_GEAR_UPGRADE = new VaultGearUpgradeConfig().readConfig();
      VAULT_GEAR_SCALING = new VaultGearScalingConfig().readConfig();
      VAULT_SIZE = new VaultSizeConfig().readConfig();
      SOUL_SHARD = new SoulShardConfig().readConfig();
      ETERNAL_ATTRIBUTES = new EternalAttributeConfig().readConfig();
      ETERNAL_AURAS = new EternalAuraConfig().readConfig();
      VAULT_GEAR_UTILITIES = new VaultGearUtilitiesConfig().readConfig();
      VAULT_GEAR_CRAFTING_SCALING = new VaultGearCraftingScalingConfig().readConfig();
      DIFFICULTY_DESCRIPTION = new DifficultyDescriptionConfig().readConfig();
      SCALING_CHEST_REWARDS = new VaultScalingChestConfig().readConfig();
      VAULT_INHIBITOR = new VaultInhibitorConfig().readConfig();
      FLAWED_RUBY = new FlawedRubyConfig().readConfig();
      ETCHING = new EtchingConfig().readConfig();
      RAID_CONFIG = new RaidConfig().readConfig();
      RAID_MODIFIER_CONFIG = new RaidModifierConfig().readConfig();
      RAID_EVENT_CONFIG = new RaidEventConfig().readConfig();
      VAULT_CHARM = new VaultCharmConfig().readConfig();
      MYSTERY_EGG = new MysteryEggConfig().readConfig();
      MYSTERY_HOSTILE_EGG = new MysteryHostileEggConfig().readConfig();
      VAULT_RUNE = new VaultRuneConfig().readConfig();
      Vault.LOGGER.info("Vault Configs are loaded successfully!");
   }
}
